name: python

on:
  push

jobs:
  build:
    name: "Test python run"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8.4
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.4
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run script
        run: |
          python ./ci/build.py